export const MATERIALS = [
    'paper',
    'photographic support',
    'cardboard',
    'ink',
    'pencil',
    'chalk',
    'baryta paper',
    'watercolor (paint)',
    'silver (metal)',
    'linen (material)',
    'wood (plant material)',
    'glass',
    'porcelain',
    'copper (metal)',
    'glaze',
    'silk',
    'printing ink',
    'oil paint (paint)',
    'gold (metal)',
    'deck paint',
    'earthenware',
    'India ink (ink)',
    'bronze (metal)',
    'iron (metal)',
    'RC paper',
    'metal',
    'brass (alloy)',
    'cotton (textile)',
    'leather',
    'canvas',
    'paint (coating)',
    'Japanese paper (handmade paper)',
    'cobalt (mineral)',
    'panel',
    'textile materials',
    'oak (wood)',
    'tin glaze',
    'wool',
    'lead (metal)',
    'tin (metal)',
    'parchment (animal material)',
    'gouache (paint)',
    'stoneware',
    'graphite (mineral)',
    'transparant paper',
    'gilding (material)',
    'velvet (fabric weave)',
    'ivory',
    'gold leaf',
    'tracing paper',
    'walnut (hardwood)',
    'lacquer (coating)',
    'Japanese paper',
    'prepared paper',
    'rope',
    'pipe clay',
    'ebony (wood)',
    'plastic (organic material)',
    'celluloid (cellulosic)',
    'satin',
    'mother of pearl',
    'lead glaze',
    'marble (rock)',
    'photographic film (photographic materials)',
    'bone china (material)',
    'mahogany (wood)',
    'zinc',
    'newsprint',
    'terracotta (clay material)',
    'bone (material)',
    'silver thread',
    'batiste',
    'rosewood (wood)',
    'steel (alloy)',
    'pressure-sensitive tape',
    'cloth',
    'ball-point pens',
    'gypsum',
    'pine (wood)',
    'marbled paper',
    'beech (wood)',
    'linden',
    'corrugated board',
    'maple (wood)',
    'horn (animal material)',
    'watercolor paper',
    'boxwood',
    'sandstone',
    'blotting paper',
    'China paper',
    'engobe',
    'diamond (mineral)',
    'silver stain',
    'aluminum (metal)',
    'felt (textile)',
    'nickel (metal)',
    'pearl',
    'poster paint',
    'wax',
    'taffeta'
  ];

export const TECHNIQUES = [
    'etching',
    'engraving',
    'albumen print',
    'pen',
    'gelatin silver print',
    'letterpress printing',
    'brush',
    'collotype',
    'writing (processes)',
    'striking (metalworking)',
    'drypoint',
    'printing',
    'painting',
    'vitrification',
    'gilding',
    'printing block',
    'color woodcut',
    'steel engraving',
    'casting',
    'slide',
    'cutting',
    'damask',
    'bobbin lace',
    'drawing',
    'embroidering',
    'salted paper print',
    'photolithography',
    'glassblowing',
    'cyanotype',
    'majolica',
    'block printing (relief printing process)',
    'carbon print',
    'forging',
    'gelatin silver slide on glass',
    'collage',
    'inkjet print',
    'lacquering',
    'perforating',
    'counterproof',
    'photochrom',
    'knitting',
    'grinding',
    'retroussage',
    'snipping',
    'ferrotyping',
    'sewing',
    'nishiki-e',
    'manuscript',
    'ambrotype',
    'relief printing',
    'pencil',
    'polishing',
    'tapestry',
    'Valenciennes lace',
    'decorated paper',
    'Mechlin (lace)',
    'wet collodion negative',
    'sawing',
    'soldering',
    'twill',
    'stapling',
    'inlay (process)',
    'braiding',
    'Lille lace',
    'combed marbled paper',
    'Alençon lace',
    'Binche lace',
    'mixed lace',
    'filigree',
    'printed matter',
    'marbled paper',
    'ball-point pens',
    'Woodburygravure',
    'Brussels bobbin lace',
    'phantasy marbled paper',
    'snail marbled paper',
    'agate marbled paper',
    'scoring',
    'ink',
    'Brussels point de gaze',
    'filing',
    'old Flemish lace',
    'Cluny lace',
    'crocheting',
    'gluing',
    'lampas (textile material)',
    'chintz',
    'stone marbled paper',
    'Brussels appliqué',
    'spanish marbled paper',
    'Venetian raised work',
    'flat Venetian (needle point)',
    'jacquard',
    'shell marbled paper',
    'blow molding',
    'chalk',
    'basting',
    'cocoa marbled paper',
    'hammering',
    'torchon lace'
  ];
